### Get all persons 
GET http://localhost:3001/api/persons

### Delete person with id 2 (Ada Lovelace)
DELETE http://localhost:3001/api/persons/2

### Get all persons again (check if Ada is gone)
GET http://localhost:3001/api/persons

### Post (Add a new person)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Rob Martinez",
    "number": "39-90-2345690"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Mary Poppins",
  "number": "123-456789"
}

### POST (test for no name)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "985-3402855"
}

### POST (test for no number)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Monkey"
}

### POST (test for name exists)
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Arto Hellas",
  "number": "39-45-765434"
}

